import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
  cosasQmeGustanMuxoEstails: {
    borderColor: "black",
    borderWidth: 3,
    borderStyle: "dashed",
    padding: 20,
    color: "black",
    textAlign: "center",
    fontWeight: "bold",
    fontStyle: "italic",
    fontSize: 16,
    backgroundColor: "lightgray",
    borderRadius: 80,
    margin: 20,
  },
  darkcosasQmeGustanMuxoEstails: {
    borderColor: "green",
    borderWidth: 3,
    borderStyle: "dashed",
    padding: 20,
    color: "orange",
    textAlign: "center",
    fontWeight: "bold",
    fontStyle: "italic",
    fontSize: 16,
    backgroundColor: "white",
    borderRadius: 100,
    margin: 20,
  },
});
